/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.floricultura.sistema.view;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.com.floricultura.sistema.model.CadastroCliente;
/**
 *
 * @author aureliosantos
 */
public class CadastroClienteView extends javax.swing.JFrame {

    /**
     * Creates new form TeleClienteFloricultura
     */
    public CadastroClienteView() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaCadastroCliente = new javax.swing.JTabbedPane();
        painelCadastrar = new javax.swing.JPanel();
        painelDadosCliente = new javax.swing.JPanel();
        jLabelNomeCliente = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jLabelSexoCliente = new javax.swing.JLabel();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jRadioButtonFemino = new javax.swing.JRadioButton();
        jLabelDataNascimento = new javax.swing.JLabel();
        jFormattedTextDataNascim = new javax.swing.JFormattedTextField();
        jLabel_CPF = new javax.swing.JLabel();
        jFormattedTextCPF = new javax.swing.JFormattedTextField();
        jLabel_EstadoCivil = new javax.swing.JLabel();
        jComboBox_Estadocivil = new javax.swing.JComboBox<>();
        jLabel_Email = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel_Telefone = new javax.swing.JLabel();
        telefone_Cliente_jFormattedText = new javax.swing.JFormattedTextField();
        tipo_Teledone_jComboBox = new javax.swing.JComboBox<>();
        jPanelDadosEndereco1 = new javax.swing.JPanel();
        jLabelRua1 = new javax.swing.JLabel();
        jTextFieldRua1 = new javax.swing.JTextField();
        jLabelNumero1 = new javax.swing.JLabel();
        jTextFieldNumero1 = new javax.swing.JTextField();
        jLabelBairro1 = new javax.swing.JLabel();
        jTextFieldBairro1 = new javax.swing.JTextField();
        jLabelCidade1 = new javax.swing.JLabel();
        jComboBoxCidade1 = new javax.swing.JComboBox<>();
        jLabelEstado1 = new javax.swing.JLabel();
        jComboBoxEstado1 = new javax.swing.JComboBox<>();
        btn_Salvar = new javax.swing.JButton();
        btn_AbaPesquisar = new javax.swing.JButton();
        btn_Sair = new javax.swing.JButton();
        painelPesquisar = new javax.swing.JPanel();
        jPanelPesquisa = new javax.swing.JPanel();
        jLabelPesquisaCPF = new javax.swing.JLabel();
        jTextFieldCPFPesquisa = new javax.swing.JTextField();
        jScrollPane_Pesquisar = new javax.swing.JScrollPane();
        jTable_Pesquisa = new javax.swing.JTable();
        btn_Pesquisar = new javax.swing.JButton();
        btn_SairPesquisar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        menuTelaCadastroCliente = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelDadosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Cliente"));

        jLabelNomeCliente.setText("Nome :");

        jTextFieldNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeClienteActionPerformed(evt);
            }
        });
        jTextFieldNomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomeClienteKeyTyped(evt);
            }
        });

        jLabelSexoCliente.setText("Sexo :");

        jRadioButtonMasculino.setText("Masculino");

        jRadioButtonFemino.setText("Feminino");

        jLabelDataNascimento.setText("Data Nascim.:");

        try {
            jFormattedTextDataNascim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextDataNascim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextDataNascimKeyTyped(evt);
            }
        });

        jLabel_CPF.setText("CPF :");

        try {
            jFormattedTextCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextCPFActionPerformed(evt);
            }
        });
        jFormattedTextCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextCPFKeyTyped(evt);
            }
        });

        jLabel_EstadoCivil.setText("Estado Civil :");

        jComboBox_Estadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione seu estado civil", "Casado", "Divorciado", "Solteiro", "Separado", "Viúvo" }));

        jLabel_Email.setText("E-mail :");

        jLabel_Telefone.setText("Telefone : ");

        try {
            telefone_Cliente_jFormattedText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tipo_Teledone_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Celular", "Comercial", "Residencial", " " }));

        javax.swing.GroupLayout painelDadosClienteLayout = new javax.swing.GroupLayout(painelDadosCliente);
        painelDadosCliente.setLayout(painelDadosClienteLayout);
        painelDadosClienteLayout.setHorizontalGroup(
            painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosClienteLayout.createSequentialGroup()
                        .addComponent(jLabelNomeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSexoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFemino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextDataNascim, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosClienteLayout.createSequentialGroup()
                        .addComponent(jLabel_CPF)
                        .addGap(24, 24, 24)
                        .addComponent(jFormattedTextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_EstadoCivil)
                        .addGap(3, 3, 3)
                        .addComponent(jComboBox_Estadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosClienteLayout.createSequentialGroup()
                        .addComponent(jLabel_Email)
                        .addGap(9, 9, 9)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Telefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefone_Cliente_jFormattedText, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(tipo_Teledone_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelDadosClienteLayout.setVerticalGroup(
            painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosClienteLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeCliente)
                    .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSexoCliente)
                    .addComponent(jRadioButtonMasculino)
                    .addComponent(jRadioButtonFemino)
                    .addComponent(jLabelDataNascimento)
                    .addComponent(jFormattedTextDataNascim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CPF)
                    .addComponent(jFormattedTextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_EstadoCivil)
                    .addComponent(jComboBox_Estadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Email)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Telefone)
                    .addComponent(telefone_Cliente_jFormattedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo_Teledone_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanelDadosEndereco1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados de Endereço\n"));

        jLabelRua1.setText("Rua :");

        jLabelNumero1.setText("Número : ");

        jTextFieldNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumero1ActionPerformed(evt);
            }
        });
        jTextFieldNumero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumero1KeyTyped(evt);
            }
        });

        jLabelBairro1.setText("Bairro :");

        jLabelCidade1.setText("Cidade : ");

        jComboBoxCidade1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cidade", "São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo\t", "São José dos Campos\t", "Santo André\t", "Ribeirão Preto\t", "Osasco\t", "Sorocaba\t", "Mauá\t", "São José do Rio Preto\t", "Mogi das Cruzes\t", "Santos\t", "Diadema\t", "Jundiaí\t", "Piracicaba\t", "Carapicuíba\t", "Bauru\t", "Itaquaquecetuba\t", "São Vicente\t", "Franca\t", "Praia Grande\t", "Guarujá\t", "Taubaté\t\t", "Suzano\t", "Taboão da Serra" }));

        jLabelEstado1.setText("Estado : ");

        jComboBoxEstado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "São Paulo", " " }));

        javax.swing.GroupLayout jPanelDadosEndereco1Layout = new javax.swing.GroupLayout(jPanelDadosEndereco1);
        jPanelDadosEndereco1.setLayout(jPanelDadosEndereco1Layout);
        jPanelDadosEndereco1Layout.setHorizontalGroup(
            jPanelDadosEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosEndereco1Layout.createSequentialGroup()
                .addGroup(jPanelDadosEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosEndereco1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelDadosEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelRua1)
                            .addComponent(jLabelBairro1))
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldRua1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jLabelNumero1))
                    .addGroup(jPanelDadosEndereco1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCidade1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDadosEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelDadosEndereco1Layout.createSequentialGroup()
                                .addComponent(jComboBoxCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabelEstado1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPanelDadosEndereco1Layout.setVerticalGroup(
            jPanelDadosEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosEndereco1Layout.createSequentialGroup()
                .addGroup(jPanelDadosEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRua1)
                    .addComponent(jTextFieldRua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumero1)
                    .addComponent(jTextFieldNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairro1)
                    .addComponent(jTextFieldBairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade1)
                    .addComponent(jComboBoxCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado1)
                    .addComponent(jComboBoxEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_AbaPesquisar.setText("Pesquisar");
        btn_AbaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AbaPesquisarActionPerformed(evt);
            }
        });

        btn_Sair.setText("Sair");
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastrarLayout = new javax.swing.GroupLayout(painelCadastrar);
        painelCadastrar.setLayout(painelCadastrarLayout);
        painelCadastrarLayout.setHorizontalGroup(
            painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDadosEndereco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Salvar)
                .addGap(18, 18, 18)
                .addComponent(btn_AbaPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Sair)
                .addGap(50, 50, 50))
            .addComponent(painelDadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        painelCadastrarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_AbaPesquisar, btn_Sair, btn_Salvar});

        painelCadastrarLayout.setVerticalGroup(
            painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrarLayout.createSequentialGroup()
                .addComponent(painelDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanelDadosEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sair)
                    .addComponent(btn_AbaPesquisar)
                    .addComponent(btn_Salvar))
                .addContainerGap())
        );

        painelCadastrarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_AbaPesquisar, btn_Sair, btn_Salvar});

        telaCadastroCliente.addTab("Cadastrar Cliente", painelCadastrar);

        jPanelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pesquisar", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabelPesquisaCPF.setText("Digite o CPF :");

        jTextFieldCPFPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFPesquisaActionPerformed(evt);
            }
        });
        jTextFieldCPFPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCPFPesquisaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelPesquisaLayout = new javax.swing.GroupLayout(jPanelPesquisa);
        jPanelPesquisa.setLayout(jPanelPesquisaLayout);
        jPanelPesquisaLayout.setHorizontalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelPesquisaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCPFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPesquisaLayout.setVerticalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesquisaCPF)
                    .addComponent(jTextFieldCPFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTable_Pesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id_Clinete", "Nome Cliente", "CPF Cliente", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane_Pesquisar.setViewportView(jTable_Pesquisa);

        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });

        btn_SairPesquisar.setText("Sair");
        btn_SairPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairPesquisarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");

        btnExcluir.setText("Excluir");

        javax.swing.GroupLayout painelPesquisarLayout = new javax.swing.GroupLayout(painelPesquisar);
        painelPesquisar.setLayout(painelPesquisarLayout);
        painelPesquisarLayout.setHorizontalGroup(
            painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisarLayout.createSequentialGroup()
                .addGap(466, 466, 466)
                .addComponent(btn_Pesquisar)
                .addContainerGap(547, Short.MAX_VALUE))
            .addGroup(painelPesquisarLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_SairPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelPesquisarLayout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addGroup(painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane_Pesquisar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                        .addComponent(jPanelPesquisa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(88, Short.MAX_VALUE)))
        );
        painelPesquisarLayout.setVerticalGroup(
            painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisarLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btn_Pesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE)
                .addGroup(painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btn_SairPesquisar))
                .addContainerGap())
            .addGroup(painelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPesquisarLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(138, 138, 138)))
        );

        telaCadastroCliente.addTab("Pesquisar", painelPesquisar);

        jMenu1.setText("File");
        menuTelaCadastroCliente.add(jMenu1);

        jMenu2.setText("Edit");
        menuTelaCadastroCliente.add(jMenu2);

        setJMenuBar(menuTelaCadastroCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaCadastroCliente, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaCadastroCliente)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeClienteActionPerformed

    private void jTextFieldNomeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeClienteKeyTyped
        // TODO add your handling code here:
        if(jTextFieldNomeCliente.getText().length()>60){
            evt.consume();
            JOptionPane.showMessageDialog(this, " Favor abrevie seu sobre nome ");
        }
    }//GEN-LAST:event_jTextFieldNomeClienteKeyTyped

    private void jFormattedTextCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextCPFActionPerformed

    }//GEN-LAST:event_jFormattedTextCPFActionPerformed

    private void jFormattedTextCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextCPFKeyTyped
        char CPF= evt.getKeyChar();
        
               if(((CPF<'0')||(CPF>'9'))&&(CPF != KeyEvent.VK_BACK_SPACE)){
                   evt.consume();
                 JOptionPane.showMessageDialog(this,"Insira Apenas numeros!");
               }
    }//GEN-LAST:event_jFormattedTextCPFKeyTyped

    private void jTextFieldNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumero1ActionPerformed
       
    }//GEN-LAST:event_jTextFieldNumero1ActionPerformed

    private void jTextFieldNumero1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumero1KeyTyped
        char numero= evt.getKeyChar();
        
               if(((numero<'0')||(numero>'9'))&&(numero != KeyEvent.VK_BACK_SPACE)){
                   evt.consume();
                 JOptionPane.showMessageDialog(this,"Insira Apenas numeros!");
               }
    }//GEN-LAST:event_jTextFieldNumero1KeyTyped

    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
        System.exit(0);       // Botão para sair do sistema
    }//GEN-LAST:event_btn_SairActionPerformed

    private void btn_AbaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AbaPesquisarActionPerformed
        telaCadastroCliente.setSelectedIndex(1); // Alterar entre as telas
        
    }//GEN-LAST:event_btn_AbaPesquisarActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
         CadastroCliente dadosCliente = new CadastroCliente();

        String nome = jTextFieldNomeCliente.getText();

        if(jRadioButtonMasculino.isSelected()){
            dadosCliente.setSexoCliente("Masculino");
        }
        else if(jRadioButtonFemino.isSelected()){
            dadosCliente.setSexoCliente("Feminino");
        }
        String dataRecebida = jFormattedTextDataNascim.getText();
        String cpfRecebido = jFormattedTextCPF.getText();
        String estadoCivil = jComboBox_Estadocivil.getSelectedItem().toString();
        String email = jTextFieldEmail.getText();
        String rua = jTextFieldRua1.getText();
        String numero = jTextFieldNumero1.getText();
        String bairro = jTextFieldBairro1.getText();
        String cidade = jComboBoxCidade1.getSelectedItem().toString();
        String estado = jComboBoxEstado1.getSelectedItem().toString();

        if(cpfRecebido.trim().equals("")|| nome.trim().equals("")||dataRecebida.trim().equals("")
            ||cpfRecebido.trim().equals("")||rua.trim().equals("")||numero.trim().equals("") || bairro.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Por Favor Preencha campos Obrigatorio");
            jFormattedTextCPF.setBackground(Color.yellow);
            jTextFieldNomeCliente.setBackground(Color.yellow);
            jFormattedTextDataNascim.setBackground(Color.yellow);
        }
        else{
            jFormattedTextCPF.setBackground(Color.white);
            jTextFieldNomeCliente.setBackground(Color.white);
            jFormattedTextDataNascim.setBackground(Color.white);
        }

        dadosCliente.setNomeCliente(nome);
        dadosCliente.setDataNascimento(dataRecebida);
        dadosCliente.setcpfCliente(cpfRecebido);
        dadosCliente.setestadoCivil(estadoCivil);
        dadosCliente.setemailCliente(email);
        dadosCliente.setNumeroC(numero);
        dadosCliente.setRuaCliente(rua);
        dadosCliente.setBairroCliente(bairro);
        dadosCliente.setCidadeCliente(cidade);
        dadosCliente.setEstadoCliente(estado);
        
        
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void jTextFieldCPFPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFPesquisaActionPerformed

    private void jTextFieldCPFPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCPFPesquisaKeyTyped
      
        char c = evt.getKeyChar();
               if(((c<'0')||(c>'9'))&&(c != KeyEvent.VK_BACK_SPACE)){
                   evt.consume();
                 JOptionPane.showMessageDialog(this,"Para Pesquisar insira APENAS numeros!");
               }
                     
    }//GEN-LAST:event_jTextFieldCPFPesquisaKeyTyped

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
       DefaultTableModel tmcliente = new DefaultTableModel();
       
       tmcliente.addColumn("ID CLIENTE");
       tmcliente.addColumn("Nome");
       tmcliente.addColumn("CPF");
       tmcliente.addColumn("E-Mail");
       
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void btn_SairPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SairPesquisarActionPerformed

    private void jFormattedTextDataNascimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextDataNascimKeyTyped
            char datanasci= evt.getKeyChar();
        
               if(((datanasci<'0')||(datanasci>'9'))&&(datanasci != KeyEvent.VK_BACK_SPACE)){
                   evt.consume();
                 JOptionPane.showMessageDialog(this,"Insira Apenas numeros!");
               }        
    }//GEN-LAST:event_jFormattedTextDataNascimKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btn_AbaPesquisar;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JButton btn_SairPesquisar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JComboBox<String> jComboBoxCidade1;
    private javax.swing.JComboBox<String> jComboBoxEstado1;
    private javax.swing.JComboBox<String> jComboBox_Estadocivil;
    private javax.swing.JFormattedTextField jFormattedTextCPF;
    private javax.swing.JFormattedTextField jFormattedTextDataNascim;
    private javax.swing.JLabel jLabelBairro1;
    private javax.swing.JLabel jLabelCidade1;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEstado1;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelNumero1;
    private javax.swing.JLabel jLabelPesquisaCPF;
    private javax.swing.JLabel jLabelRua1;
    private javax.swing.JLabel jLabelSexoCliente;
    private javax.swing.JLabel jLabel_CPF;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_EstadoCivil;
    private javax.swing.JLabel jLabel_Telefone;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanelDadosEndereco1;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JRadioButton jRadioButtonFemino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JScrollPane jScrollPane_Pesquisar;
    private javax.swing.JTable jTable_Pesquisa;
    private javax.swing.JTextField jTextFieldBairro1;
    private javax.swing.JTextField jTextFieldCPFPesquisa;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldNumero1;
    private javax.swing.JTextField jTextFieldRua1;
    private javax.swing.JMenuBar menuTelaCadastroCliente;
    private javax.swing.JPanel painelCadastrar;
    private javax.swing.JPanel painelDadosCliente;
    private javax.swing.JPanel painelPesquisar;
    private javax.swing.JTabbedPane telaCadastroCliente;
    private javax.swing.JFormattedTextField telefone_Cliente_jFormattedText;
    private javax.swing.JComboBox<String> tipo_Teledone_jComboBox;
    // End of variables declaration//GEN-END:variables
}
