/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.lojainformaticaado2Views;

import com.mycompany.lojainformaticaado2.controller.LojaInformaticaController;
import com.mycompany.lojainformaticaado2.model.Computador;
import com.mycompany.lojainformaticaado2DAO.LojaInformaticaDAO;
import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aureliosantos
 */
public class LojaInformaticaConsultaView extends javax.swing.JFrame {

    /**
     * Creates new form LojaInformaticaConsultaView
     */
    public LojaInformaticaConsultaView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_excluir = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Pesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_computador = new javax.swing.JTable();
        jCombo_marca = new javax.swing.JComboBox<>();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_Editar.setText("Editar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });

        tbl_computador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Marca", "SO", "HD", "PROCESSADOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_computador);

        jCombo_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Marca", "Aurélio Bispo", "DELL", "HP", "LENOVO" }));

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addComponent(jCombo_marca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Editar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Pesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Editar, btn_Pesquisar, btn_excluir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCombo_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btn_excluir)
                        .addGap(37, 37, 37)
                        .addComponent(btn_Editar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_voltar, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Editar, btn_Pesquisar, btn_excluir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
         int retorno = JOptionPane.showConfirmDialog(this, "Deseja realmente voltar ? ", " Deseja Voltar?",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if ( retorno ==0 ){
            this.dispose();
        }
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        String marca = jCombo_marca.getSelectedItem().toString();
        ArrayList<Computador> listaComputador = LojaInformaticaDAO.consultarComputador(marca);
       
        DefaultTableModel tmComputadores = (DefaultTableModel) tbl_computador.getModel();
                  
      
        tmComputadores.setRowCount(0);
        
       
        for (Computador c : listaComputador) {
            tmComputadores.addRow(new Object[]{String.valueOf(c.getID_computador()),c.getmarca(),c.getSO(),c.getHD(),c.getProcessador()});
                    }
  
        tbl_computador.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbl_computador.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbl_computador.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbl_computador.getColumnModel().getColumn(3).setPreferredWidth(100);
        tbl_computador.getColumnModel().getColumn(4).setPreferredWidth(100);
        
        
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int numeroLinha = -1;
        if(tbl_computador.getRowCount()>0){
            
            numeroLinha = tbl_computador.getSelectedRow();
            
            if(numeroLinha > -1){
                
                int ID_computador = Integer.parseInt(tbl_computador.getModel().getValueAt(numeroLinha,0).toString());
            
          
            
            
            if(LojaInformaticaController.excluir(ID_computador)){
                
                JOptionPane.showMessageDialog(this, "Computador Excluido com Sucesso!");
                
            }
            else{
                JOptionPane.showMessageDialog(this, "ERRO ao excluir o computador selecionado!");
            }
                
            }
            else {
                JOptionPane.showMessageDialog(this, "Selecione um computador para realizar a Exclusão!");
            }
            
            
        }
       
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
       
        Computador comp = new Computador();
        
        if(tbl_computador.getRowCount()>0)
        {
            //Resgato o número da linha pelo JTable
            int editarLinha = tbl_computador.getSelectedRow();
            
            //Resgato o ID (oculto) do cliente pelo JTableModel
            int ID_computador = Integer.parseInt(tbl_computador.getModel().getValueAt(editarLinha, 0).toString());
            comp.setID_computador(ID_computador);
           
            
            //Passo o objeto para a tela de Cadastro informando que é alteração
            LojaInformaticaView tela = new LojaInformaticaView();
            tela.Modo = "editar";
            
            //Exibir o JFrame
            tela.setVisible(true);
        
        }
        
        else{
           
            JOptionPane.showMessageDialog(this, "Selecione um Computador da tabela!");
        }
         
       
    }//GEN-LAST:event_btn_EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LojaInformaticaConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LojaInformaticaConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LojaInformaticaConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LojaInformaticaConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LojaInformaticaConsultaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JComboBox<String> jCombo_marca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_computador;
    // End of variables declaration//GEN-END:variables
}
